# Used by "mix format"
[
  inputs: [
    "{mix,.formatter}.exs",
    "{config,lib,test}/**/*.{ex,exs}"
  ],
  locals_without_parens: [
    edge: 1,
    edge: 2,
    one_to_one: 1,
    one_to_one: 2,
    one_to_one: 3,
    one_to_many: 1,
    one_to_many: 2,
    one_to_many: 3,
    zero_or_one_to_many: 1,
    zero_or_one_to_many: 2,
    zero_or_one_to_many: 3,
    exactly_one_to_many: 1,
    exactly_one_to_many: 2,
    exactly_one_to_many: 3,
    many_to_many: 1,
    many_to_many: 2,
    many_to_many: 3,
    has_one: 1,
    has_one: 2,
    has_one: 3,
    has_many: 1,
    has_many: 2,
    has_many: 3,
    maybe_has_many: 1,
    maybe_has_many: 2,
    maybe_has_many: 3,
    has_at_least_one: 1,
    has_at_least_one: 2,
    has_at_least_one: 3,
    has_and_belongs_to_many: 1,
    has_and_belongs_to_many: 2,
    has_and_belongs_to_many: 3,
    field: 2,
    field: 3,
    column: 2,
    column: 3,
    pk: 2,
    pk: 3,
    primary_key: 2,
    primary_key: 3,
    fk: 2,
    fk: 3,
    foreign_key: 2,
    foreign_key: 3
  ]
]
